#!/usr/bin/env sh

MONITOR=$1

killall -q waybar

# Wait until process dies
while pgrep -u $UID -x waybar >/dev/null; do sleep 1; done

hyprctl keyword monitor $MONITOR,disable

# Re-start waybar
waybar -c ~/.config/waybar-hypr/config -s ~/.config/waybar-hypr/style.css
